### ISSUE TITLE
incbin bug

### ISSUE THREAD

**Issue by bu95bunny** [NF6X/asmx#1]
This is the official bug.
When including a binary file with incbin, it cuts the file at "1A" byte.
i.e. I got a "binary.bin" file, which is "00 11 22 33 **1A** 44 55 66" in hex.
So I do **incbin "binary.bin"** in my asm source file and asmx includes only "00 11 22 33" and it stops right before 1A byte. Somehow, it considers 1A byte as the end of the file.
This bug appears only on windows and the only solution atm is to build asmx with cygwin.

**Comment by NF6X** [comment]
I am not the original author of asmx. This repository is my fork which I made to fix compilation in newer versions of Mac OS X which no longer support the PPC architecture (and the fix turned out to be trivial).

The original author's README.txt file advises Windows users to compile under Cygwin, and I agree. This program was written for use in Unix-like environments, and Cygwin provides a Unix-like environment for Windows platforms.
